### ISSUE TITLE
Missing hint that arm architecture is unsupported

### ISSUE THREAD

**Issue by Sohn123** [SEPIA-Framework/sepia-stt-server#1]
Hey,

I tried to install the dockerimage on my raspberry 4. But it didn't work and at first I couldn't figure out why. Then I looked in the description of the image and saw that it only supports amd64 architecture right now. Maybe you can add a little disclaimer. On my amd64 machine it worked like a charm ;)

**Comment by fquirin** [comment]
Yes sorry, the container only exists for am64/x86 machines at the moment. Somehow I'd expect that Docker itself would warn you about this ... but maybe there are actually containers that work on both architectures at the same time.
Usually I don't recommend installing anything else than the SEPIA server on a RPi. To my mind Docker creates too much overhead on such a small system ... but on a Pi 4 it could make sense ^^.
