### ISSUE TITLE
Sprache ändern

### ISSUE THREAD

**Issue by mawoka-myblock** [SEPIA-Framework/sepia-stt-server#2]
Wie ändere ich die Sprache von dem STT Modul?

**Comment by fquirin** [comment]
Hi,

die Sprache wird über das Sprachmodell gewechselt. Für Deutsch muss dafür zunächst das Modell runtergeladen werden:

https://goofy.zamia.org/zamia-speech/asr-models/kaldi-generic-de-tdnn_f-r20190328.tar.xz

Das wird dann in einen Ordner entpackt, auf den der Server Zugriff hat. Beim Docker Container Beispiel wäre das: `/home/[my user]/sepia-stt-share`

Danach kann über den SEPIA Control HUB auf der Seite "Speech Recognition" (oder über das HTTP Interface des Servers) der Pfad zum neuen Modell angegeben werden.

**Comment by mawoka-myblock** [comment]
Ich habe es in den folgenden Ordner kopiert : /home/user/sepia-share-sst/kaldi-models
Dann habe ich den Befehl dicker run --rm --name=sepia_sst u.s.w ausgeführt.
Dicker sagt folgendes:

**Comment by fquirin** [comment]
Moin,
Scheinbar läuft der Container noch, was aber ok ist. Falls der Container gestoppt wurde und sich nicht automatisch entfernt hat kannst du noch folgendes versuchen `docker rm sepia_stt` und danach den Container neustarten.

Wenn der Container läuft und du die Datei in den shared Ordner des Containers kopiert hast, kannst du direkt über den SEPIA Control HUB das Modell ändern. Hier ein Screenshot der Seite die ich meine (v2.4.1):

![image](https://user-images.githubusercontent.com/18550513/83722835-f44b1a80-a63d-11ea-9d1c-cb75b7e94986.png)

Bei  dem Befehl:
```
docker run --rm --name=sepia_stt -d -p 9000:8080 -v /home/[my user]/sepia-stt-share:/apps/share sepia/stt-server:beta2.1
```

Sollte der Eintrag fürs Modell ungefähr so aussehen, abhängig von deinen genauen Ordner Namen:
`/apps/share/kaldi_models/kaldi-generic-de-tdnn_f...`

Als Server zum Verbinden oben müsste etwa sowas stehen:
`http://[IP-des-PCs-mit-Docker]:9000/stt`

Hilft das? :innocent: 
Ich verspreche dazu bald eine ordentliche Anleitung zu schreiben :-)

**Comment by mawoka-myblock** [comment]
Er sagt mir jetzt, dass ich ein Auth Token brauche... Wo finde ich es?

**Comment by fquirin** [comment]
> Er sagt mir jetzt, dass ich ein Auth Token brauche... Wo finde ich es?

Ah, vergessen, das Token [ist einfach "test"](https://github.com/SEPIA-Framework/sepia-stt-server#rest-interface).

> Ach noch eine Frage... Startet der Docker container automatisch beim hochfahren?

Beim Hochfahren deines PCs? Eigentlich nicht aber kommt vermutlich auf deine Docker Konfiguration an :thinking:

**Comment by mawoka-myblock** [comment]
Und wie mache ich das, dass der container startet? Einfach den Befehl in die Crontab?

**Comment by mawoka-myblock** [comment]
Es funktioniert immer noch nicht... Er meint, dass ich den Pfad noch mal überpüfen soll...

**Comment by fquirin** [comment]
Ist das dein Linux Arbeitsrechner oder ein System, dass möglichst unbetreut im Hintergrund laufen soll? 

Crontab wäre möglich, Docker selber hat aber auch eine [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/). Ich habe damit auch noch nicht viel experimentiert, aber ein Container mit dem "--restart" Flag sollte starten sobald der Docker Daemon startet und für den Daemon gibt es glaube ich einen System Service.

**Comment by mawoka-myblock** [comment]
OK aber es klappt immer noch nicht mit dem Spraxhmodell ändern...

**Comment by mawoka-myblock** [comment]
sollte der Befehl den Container starten: docker run --rm --name=sepia_stt -d -p 9000:8080 -v /home/[my user]/sepia-stt-share:/apps/share sepia/stt-server:beta2.1 ? wen ja, er tut es nicht... nur der Befehl startet den Container: docker run --rm --name=sepia_stt -d -p 9000:8080 sepia/stt-server:beta2.1

**Comment by fquirin** [comment]
Der Teil ` -v /home/[my user]/sepia-stt-share:/apps/share` macht Probleme?
Gibt es eine Fehlermeldung?

Ein paar Erläuterungen dazu:
- Der Befehl bindet den Ordner ein, der zwischen Host System und Docker Container geteilt wird
- `/home/[my user]/sepia-stt-share` ist der Ordner auf deinem Host System. '/home/[my user]' ist entsprechend mit deinem Home-Verzeichnis zu ersetzen. 'sepia-stt-share' ist im Grunde beliebig aber bietet sich an.
- `/apps/share` ist der Ordner innerhalb des Docker Containers, der dann mit dem Inhalt deines Host Systems synchronisiert wird
- Im Beispiel oben `/apps/share/kaldi_models/kaldi-generic-de-...` entspräche das also z.B. dem Ordner `/home/florian/sepia-stt-share/kaldi_models/kaldi-generic-de-...` für den User `florian`

**Comment by mawoka-myblock** [comment]
Docker gibt keinen Fehler aus nur SEPIA sagt, dass der Pfad falsch ist

**Comment by fquirin** [comment]
Wie lautet denn dein Ordner wohin du das deutsche Sprachmodell entpackt hast?

**Comment by mawoka-myblock** [comment]
/home/minecraft/sepia-stt-share/kaldi_models/

**Comment by mawoka-myblock** [comment]
minecraft ist der user

**Comment by fquirin** [comment]
Und dein Sprachmodell liegt in:
`/home/minecraft/sepia-stt-share/kaldi_models/kaldi-generic-de-tdnn_f-r20190328` ?

Dann wäre das Docker Kommando:
`docker run --rm --name=sepia_stt -d -p 9000:8080 -v /home/minecraft/sepia-stt-share:/apps/share sepia/stt-server:beta2.1`

Und der Eintrag im HUB:
`/apps/share/kaldi_models/kaldi-generic-de-tdnn_f-r20190328`

**Comment by mawoka-myblock** [comment]
ja

**Comment by mawoka-myblock** [comment]
docker run --rm --name=sepia_stt -d -p 9000:8080 -v /home/minecraft/sepia-stt-share:/apps/share sepia/stt-server:beta2.1
Danach ist der STT Server nicht erreichbar, nachdem ich diesen Befehl ausgeführt habe...

**Comment by fquirin** [comment]
Hattest du den Teil mit der 'share-folder.zip' aus der [STT Server README](https://github.com/SEPIA-Framework/sepia-stt-server#using-the-docker-image) schon ausgeführt?
Alles was nach ...
> To change the server settings, add your own ASR models, do language model customization or to capture your recordings for later you can use the internal 'share' folder like this: ...

... kommt.
Vielleicht fehlt dem Container was im shared folder.
Du kannst dann auch die `sepia_stt_server/app.conf` benutzen um den Model Pfad permanent festzulegen.

Du kannst auch den Container mal testweise ohne den `-d` Parameter starten, dann kommt der Log direkt in die Konsole. Stoppen dann mit CTRL+C.

**Comment by mawoka-myblock** [comment]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"-d\": executable file not found in $PATH": unknown.

**Comment by fquirin** [comment]
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: "-d": executable file not found in $PATH": unknown.

Uh, das sagt mir jetzt spontan nix O_o

**Comment by mawoka-myblock** [comment]
Das habe ich in die app.conf eingetragen: kaldi_model_path=/opt/kaldi/model/kaldi-generic-de-tdnn_f-r20190328

**Comment by fquirin** [comment]
Kommt das mit diesem Befeh?
`docker run --rm --name=sepia_stt -p 9000:8080 -v /home/minecraft/sepia-stt-share:/apps/share sepia/stt-server:beta2.1`

**Comment by fquirin** [comment]
> Das habe ich in die app.conf eingetragen: kaldi_model_path=/opt/kaldi/model/kaldi-generic-de-tdnn_f-r20190328

`/opt/kaldi/model` sollte `/apps/share/kaldi_models` sein, es liegt ja im shared

**Comment by mawoka-myblock** [comment]
Das kommt bei dem Befehl:

sudo docker run --rm --name=sepia_stt -p 9000:8080 -v /home/minecraft/sepia-stt-share:/apps/share sepia/stt-server:beta2.1
Starting nginx: nginx.
   INFO Config name: SEPIA-Custom
   INFO Loading Kalid model /opt/kaldi/model/kaldi-generic-de-tdnn_f-r20190328 ...
Traceback (most recent call last):
  File "sepia_stt_server.py", line 390, in <module>
    main()
  File "sepia_stt_server.py", line 370, in main
    set_default_decoder(Decoder(config.kaldi_model_path))
  File "sepia_stt_server.py", line 144, in __init__
    self.kaldi_model = KaldiNNet3OnlineModel(self.model_dir, acoustic_scale=1.0, beam=7.0, frame_subsampling_factor=3)
  File "kaldiasr/nnet3.pyx", line 106, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__ (kaldiasr/nnet3.cpp:2528)
Exception: /opt/kaldi/model/kaldi-generic-de-tdnn_f-r20190328/conf/mfcc_hires.conf not found.

**Comment by mawoka-myblock** [comment]
Habe das Problem gelöst... Ich bin einfach zu inkompetent... in der app.conf stand: kaldi_model_path=/opt/kaldi/model/kaldi-generic-de-tdnn_f-r20190328

Habe es jetzt in folgenden Pfad geändert:  /apps/share/kaldi_models/kaldi-generic-de-tdnn_f-r20190328

Und jetzt funktioniert es... Aber ich habe das hintere teil nur geändert, nicht das /opt/...

**Comment by fquirin** [comment]
> `/opt/kaldi/model` sollte `/apps/share/kaldi_models` sein, es liegt ja im shared

Mir is auch gerade noch eingefallen, um den Container zu stoppen geht nicht CTRL+C sonder man muss in einer zweiten Session `sudo docker stop sepia_stt` eingeben

**Comment by mawoka-myblock** [comment]
Ich muss dir noch eine Sache sagen: Das was du da geleistet hast, das ist der Hammer! Das Interface sieht gut aus, es funktioniert alles relativ gut und dass du auch noch so schnell und gut hilfst... Du machst das wirklich gut! Danke, für dieses tolle Projekt!

**Comment by fquirin** [comment]
Danke! :smiley: 
Beim STT Server gibt es noch einiges zu verbessern aber mit dem Rest bin ich auch schon ganz zufrieden ;-)

**Comment by mawoka-myblock** [comment]
Wenn man ihn endlich richtig eingerichtet hat, funktioniert er aber auch gut!

**Comment by fquirin** [comment]
Ja, es gibt die Möglichkeit das komplette Sprachmodell anzupassen, das ist allerdings einer der Punkte, die ich meinte mit "es noch einiges zu verbessern", da es etwas komplizierter ist und komplett undokumentiert bisher :see_no_evil: . Richtig gemacht kann es allerdings die Erkennungsrate enorm verbessern (auf Kosten eines kleinere Vokabulars).

Ich versuche mal kurz eine grobe Übersicht zu geben:
- Zunächst müssen fehlende Wörter inklusive ihrer Phonems (zur Zeit per Hand) ergänzt werden in der Lexikon Datei des Modells: `[MODEL-FOLDER]/data/local/dict/lexicon.txt`. Am Besten guckt man sich die Phonems dazu bei anderen, ähnlichen Wörter ab
- Dann muss im Ordner `/apps/share/lm_corpus/` (sprich `/home/minecraft/sepia-stt-share/lm_corpus` des shared folders) eine Datei erstellt werden die `sentences_de.txt` (für deutsche Modelle) oder `sentences_en.txt` (für Englische Modelle) heißt.
- In diese Datei schreibt man Zeile für Zeile Sätze die erkannt werden sollen. Aus diesen Sätzen wird später das neue Modell erstellt, das heißt nur Wörter die in einem der Sätze vorkommen können später erkannt werden. Das Modell kann aber später auch "improvisieren" sprich Sätze zusammenbauen aus bekannten Wörtern die nicht 100% so aufgeschrieben wurden.
- Dann öffnet man den SEPIA Control HUB, geht auf die "Speech Recognition" Seite, gibt bei "version" etwas ein (wird an den Namen des neuen Modells angehängt), wählt die Sprache und drückt "Adapt LM"

Soweit die Theorie ^^. Ich fürchte allerdings in der 2.1 Beta von STT Server ist ein Bug drin, den man vorher beheben muss, denn er sucht bei der Model Adaptation im Ordner "/opt/kaldi/model/kaldi-generic-[LANG_CODE]-tdnn" der neue Ordner ist aber "/opt/kaldi/model/kaldi-generic-[LANG_CODE]-tdnn_f" :-/
Dazu muss man den Container im Terminal Modus starten und die Datei `/apps/sepia-stt-server/lm_adapt/adapt_build_move_clean.sh` bearbeiten. Wie das genau geht ist wieder ein neues Tutorial :see_no_evil:

**Comment by mawoka-myblock** [comment]
OK ich glaube, ich lasse die Finger mal davon, bevor ich ein neuen "Issue" öffnen muss weil ich das Programm "zerstört" habe :laughing::laughing:

**Comment by fquirin** [comment]
:-p In Zukunft wird es hoffentlich deutlich einfacher ;-)

**Comment by mawoka-myblock** [comment]
3 Jahre später lese ich mir das ganze hier nochmal durch: Wenn ich an deiner Stelle gewesen wäre, hätte ich den Issue hier einfach geschlossen und wirklich keinen Bock gehabt, so Fragen zu beantworten, die Google auch innerhalb von 2 Minuten hätte beantworten können. Deswegen: Respekt, dass du so ausführlich und freundlich auf noch so unnötige Fragen geantwortet hast.
