### ISSUE TITLE
ASR Model Paths are wrong

### ISSUE THREAD

**Issue by eternalliving** [SEPIA-Framework/sepia-stt-server#6]
Hi,
I'm trying to test the STT server, I managed to get it running and from the development test page I am able to open the connection, however when I try to send the welcome message I get a chuck processor error, Runtime error: AST model path seems to be wrong. I checked out the server.conf file and it refers to a folder ../models but there is no folder included in the git download with the models. Do you know where I can get the ASR models from? It's trying to use the vosk-en one but I'm guessing I don't have it? Or is it located somewhere else? 
Thanks for any help you can give

ERROR:    ChunkProcessor - Failed to create processor
Traceback (most recent call last):
  File "/home/**/SEPIA/sepia-stt-server/src/users.py", line 63, in authenticate
    send_message=self.send_message, options=processor_options)
  File "/home/**/SEPIA/sepia-stt-server/src/chunk_processor.py", line 22, in __init__
    self.processor = VoskProcessor(send_message, options)
  File "/home/**/SEPIA/sepia-stt-server/src/engine_vosk.py", line 68, in __init__
    raise RuntimeError("ASR model path seems to be wrong")
RuntimeError: ASR model path seems to be wrong

**Comment by eternalliving** [comment]
Nevermind, I found the VOSK website and downloaded the ASR models and put them in a models folder... I guess without an install guide I might be missing a few steps :(

**Comment by fquirin** [comment]
Hi @eternalliving , sorry for the missing info. Its correct the models are only included in the Docker containers.
If you run the server without Docker you can find the same models in the release section as well (and on the Vosk page as you'Ve mentioned): https://github.com/SEPIA-Framework/sepia-stt-server/releases

I will add a comment on the start page to avoid confusion :+1:
